### ISSUE TITLE
Instant force-quit on 10.9.5

### ISSUE THREAD

**Issue by AKAMEDIASYSTEM** [paulkaplan/HexUploader#1]
Attempting to open the app on a brand new Macbook Pro running 10.9.5 instantly force-closes it.

Here's my error report, if it's helpful:

Process:         HexUploader [11935]
Path:            /Applications/HexUploader.app/Contents/MacOS/HexUploader
Identifier:      me.buildaweso.HexUploader
Version:         ???
Code Type:       X86-64 (Native)
Parent Process:  launchd [265]
Responsible:     HexUploader [11935]
User ID:         421643156

Date/Time:       2014-11-21 14:05:45.952 -0500
OS Version:      Mac OS X 10.9.5 (13F34)
Report Version:  11
Anonymous UUID:  8460897D-2E92-99A1-3BFD-16B76DF0A431

Sleep/Wake UUID: 37B9D08A-0DB5-4E62-BC7F-5EAFF4A97F6F

Crashed Thread:  0

Exception Type:  EXC_CRASH (Code Signature Invalid)
Exception Codes: 0x0000000000000000, 0x0000000000000000

kernel messages:

VM Regions Near 0x7fff75c3c0a8 (cr2):
    __LINKEDIT             00007fff63295000-00007fff632a9000 [   80K] r--/rwx SM=COW  /usr/lib/dyld
--> Submap                 00007fff70000000-00007fff80000000 [256.0M] r--/rwx SM=PRV  process-only VM submap
    unused shlib __DATA    00007fff738d8000-00007fff7613b000 [ 40.4M] rw-/rw- SM=COW  system shared lib __DATA not used by this process

Thread 0 Crashed:
0   dyld                          	0x00007fff63223028 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x000000000000000d  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007fff5fbffd30
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff63223028  rfl: 0x0000000000000201  cr2: 0x00007fff75c3c0a8
  
Logical CPU:     0
Error Code:      0x020000f4
Trap Number:     133

Binary Images:
    0x7fff63222000 -     0x7fff63255817  dyld (???) <7AD43B9B-5CEA-3C7E-9836-A06909F9CA56> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 81912
    thread_create: 1
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=288K resident=228K(79%) swapped_out_or_unallocated=60K(21%)
Writable regions: Total=8444K written=0K(0%) resident=12K(0%) swapped_out=0K(0%) unallocated=8432K(100%)
 
REGION TYPE                      VIRTUAL
===========                      =======
STACK GUARD                        56.0M
Stack                              8192K
VM_ALLOCATE                           8K
__DATA                              252K
__LINKEDIT                           80K
__TEXT                              208K
mapped file                         104K
shared memory                         4K
===========                      =======
TOTAL                              64.6M

Model: MacBookPro11,2, BootROM MBP112.0138.B07, 4 processors, Intel Core i7, 2.2 GHz, 16 GB, SMC 2.18f10
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x134), Broadcom BCM43xx 1.0 (6.30.223.154.65)
Bluetooth: Version 4.2.7f3 14616, 3 services, 23 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512F, 500.28 GB
USB Device: Internal Memory Card Reader
USB Device: Communication Device
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB Receiver
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.1

**Comment by paulkaplan** [comment]
I pushed a new version, 1.1 that you might try.
