### ISSUE TITLE
OS 10.10?

### ISSUE THREAD

**Issue by jarretluft** [paulkaplan/HexUploader#2]
Hi,
Has anyone successfully used this with OS 10.10?  I'm not getting anything back when I choose the hex file.  Nothing appears in the text area, no flashing lights on the arduino indicating transmission is occuring, etc... 
I'm trying to upload to a Duemilanove, and tried a number of baud rates but same issue each attempt.

**Comment by winduptoy** [comment]
Working fine for me on 10.10.2

![screen shot 2015-04-04 at 9 31 38 pm](https://cloud.githubusercontent.com/assets/270504/6995375/0cff9044-db12-11e4-9822-b8bfdbc18f03.png)

**Comment by Spica2** [comment]
Have the same issiu with 10.10.5. Nothing's happening with a uno.

**Comment by ladislas** [comment]
same here

**Comment by ladislas** [comment]
the problem is due to the path to the arduino tools being wrong.

you can fix it yourself by using the following patch:

```diff
diff --git a/Sources/HexLoaderController.m b/Sources/HexLoaderController.m
index c70f6bf..1406996 100644
--- a/Sources/HexLoaderController.m
+++ b/Sources/HexLoaderController.m
@@ -213,8 +213,8 @@

          NSLog(@"");

-         [task setLaunchPath:@"/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avrdude"];
-         [task setCurrentDirectoryPath:@"/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/etc"];
+         [task setLaunchPath:@"/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avrdude"];
+         [task setCurrentDirectoryPath:@"/Applications/Arduino.app/Contents/Java/hardware/tools/avr/etc"];

          NSArray *args = [NSArray arrayWithObjects:
                             @"-F",
```

**Comment by cojarbi** [comment]
@ladislas where do you change the path. Can you be more specific?

**Comment by ladislas** [comment]
@cojarbi here:

https://github.com/paulkaplan/HexUploader/blob/master/Sources/HexLoaderController.m#L216

**Comment by YiorgosTheo** [comment]
@ladislas Is there a compiled version with this change? I want to send it to someone with a Mac so he can install it and upload a hex file to his Arduino Nano. The version he downloaded from the app web page does not work.

**Comment by ladislas** [comment]
@YiorgosTheo unfortunately no... I just cleaned install my mac and have removed everything. but it should be easy to clone this repo, apply the patch, compile and then to your guy

**Comment by YiorgosTheo** [comment]
@ladislas thank you! If only I had a Mac, hehe....

**Comment by paulkaplan** [comment]
Hey sorry for not paying attention to this. FWIW I fixed this problem and pushed a new build.
